import { ICategoriesReducer, IProductReducer, IAppReducer, IAdminReducer } from './reducers';
import { ILoginReducer } from './reducers/LoginReducer';

export enum ACTIONS_APP {
  FREEZE_SIDE_MENU = 'FREEZE_SIDE_MENU',
  RANDOM_INDEXS = 'RANDOM_INDEXS',
  ADD_PRODUCT = 'ADD_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  CLEAR_BASKET = 'CLEAR_BASKET',
  CURRENT_CATEGORY = 'CURRENT_CATEGORY',
  SET_DISCOUNT = 'SET_DISCOUNT',
  PLUS_COUNT_PRODUCT = 'PLUS_COUNT_PRODUCT',
  MINUS_COUNT_PRODUCT = 'MINUS_COUNT_PRODUCT',
  IS_OPEN_MODAL_ORDER = 'IS_OPEN_MODAL_ORDER',
  SEND_INFO_TG_SUCCESS = 'SEND_INFO_TG_SUCCESS',
  SEND_INFO_TG_FAILURE = 'SEND_INFO_TG_FAILURE',
  SEND_INFO_TG_REQUEST = 'SEND_INFO_TG',
  ORDER_TOTAL_MONEY = 'ORDER_TOTAL_MONEY',
  CREATE_ORDER_ON_SERVER = 'CREATE_ORDER_ON_SERVER',
  GET_USER_ORDERS = 'GET_USER_ORDERS',
  GET_USER_ORDERS_SUCCESS = 'GET_USER_ORDERS_SUCCESS',
  GET_USER_ORDERS_FAILURE = 'GET_USER_ORDERS_FAILURE',
  LOGOUT_USER = 'LOGOUT_USER',
}

export enum ACTIONS_CATEGORIES {
  GET_CATEGORIES = 'GET_CATEGORIES',
  GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE',
}

export enum ACTIONS_PRODUCTS {
  GET_PRODUCTS = 'GET_PRODUCTS',
  GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE',
}

export enum ACTIONS_LOGIN {
  APP_LOGIN_NEW_USER = 'APP_LOGIN_NEW_USER',
  APP_LOGIN_EXIST_USER = 'APP_LOGIN_EXIST_USER',
  APP_LOGOUT_ADMIN = 'APP_LOGOUT_ADMIN',
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  NEW_USER_LOGIN_SUCCESS = 'NEW_USER_LOGIN_SUCCESS',
  ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS',
  APP_LOGIN_FAILURE = 'APP_LOGIN_FAILURE',
  APP_LOGOUT_USER = 'APP_LOGOUT_USER',
}

export enum ACTIONS_ADMIN_DATA {
  GET_PRODUCTS_ADMIN = 'GET_PRODUCTS_ADMIN',
  GET_PRODUCTS_SUCCESS_ADMIN = 'GET_PRODUCTS_SUCCESS_ADMIN',
  GET_PRODUCTS_FAILURE_ADMIN = 'GET_PRODUCTS_FAILURE_ADMIN',
  GET_USERS_ADMIN = 'GET_USERS_ADMIN',
  GET_USERS_SUCCESS_ADMIN = 'GET_USERS_SUCCESS_ADMIN',
  GET_USERS_FAILURE_ADMIN = 'GET_USERS_FAILURE_ADMIN',
  CHANGE_ACCOUNT_DATA = 'CHANGE_ACCOUNT_DATA',
  CHANGE_ACCOUNT_DATA_SUCCESS = 'CHANGE_ACCOUNT_DATA_SUCCESS',
  CHANGE_ACCOUNT_DATA_FAILURE = 'CHANGE_ACCOUNT_DATA_FAILURE',
}

export interface IStore {
  categoriesReducer: ICategoriesReducer;
  productReducer: IProductReducer;
  appReducer: IAppReducer;
  loginReducer: ILoginReducer;
  adminReducer: IAdminReducer;
}
