import { ICategoriesReducer, IProductReducer, IAppReducer } from './reducers';

export enum ACTIONS_APP {
  FREEZE_SIDE_MENU = 'FREEZE_SIDE_MENU',
  RANDOM_INDEXS = 'RANDOM_INDEXS',
  ADD_PRODUCT = 'ADD_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  CLEAR_BASKET = 'CLEAR_BASKET',
  CURRENT_CATEGORY = 'CURRENT_CATEGORY',
  SET_DISCOUNT = 'SET_DISCOUNT',
  PLUS_COUNT_PRODUCT = 'PLUS_COUNT_PRODUCT',
  MINUS_COUNT_PRODUCT = 'MINUS_COUNT_PRODUCT',
  IS_OPEN_MODAL_ORDER = 'IS_OPEN_MODAL_ORDER',
  SEND_INFO_TG_SUCCESS = 'SEND_INFO_TG_SUCCESS',
  SEND_INFO_TG_FAILURE = 'SEND_INFO_TG_FAILURE',
  SEND_INFO_TG_REQUEST = 'SEND_INFO_TG',
  ORDER_TOTAL_MONEY = 'ORDER_TOTAL_MONEY',
}

export enum ACTIONS_CATEGORIES {
  GET_CATEGORIES = 'GET_CATEGORIES',
  GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE',
}

export enum ACTIONS_PRODUCTS {
  GET_PRODUCTS = 'GET_PRODUCTS',
  GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE',
}

export interface IStore {
  categoriesReducer: ICategoriesReducer;
  productReducer: IProductReducer;
  appReducer: IAppReducer;
}
